version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MSAL_CLIENT_ID=${MSAL_CLIENT_ID}
      - MSAL_TENANT_ID=${MSAL_TENANT_ID}
      - MSAL_REDIRECT_URI=${MSAL_REDIRECT_URI}
      - MSAL_POST_LOGOUT_REDIRECT_URI=${MSAL_POST_LOGOUT_REDIRECT_URI}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped