services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
      - AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID}
      - AZURE_AD_REDIRECT_URI=${AZURE_AD_REDIRECT_URI}
      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped